[package]
name = "au4a-state"
description = "Portable State 可移植状态（轨道 1.3）"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
au4a-core = { workspace = true }
au4a-kernel = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
