[package]
name = "au4a-scale"
description = "Network Scaling 网络扩展（轨道 1.9）"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
au4a-core = { workspace = true }
au4a-kernel = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
